env:
  size: 4
  target: 2048
  spawn_prob_2: 0.9

seed: 42

agent:
  hidden_dim: 128
  gamma: 0.99
  tau: 0.005
  lr: 0.0003
  alpha: null  # SAC ent_coef; null -> auto

buffer:
  capacity: 200000

train:
  steps: 200000
  batch_size: 128
  train_freq: 1
  gradient_steps: 1
  eval_max_steps: 5000

reward:
  scale: 0.1
  invalid_move_penalty: -0.5

